Repository Swivel-Finance/gost, pull requests merged in 2022-06, with the labels that each got.

#290 Address inconsistencies between lender and redeemer contracts
  build/lender/Lender.abi
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/lender.go
  build/redeemer/Redeemer.abi
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/redeemertesting/redeem_test.go
  test/lender/Lender.abi
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/lender.go
  test/redeemer/Redeemer.abi
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: enhancement

#297 Implement lend on notional
  Makefile
  build/lender/Element.bin
  build/lender/INotional.abi
  build/lender/INotional.bin
  build/lender/Interfaces.sol
  build/lender/Lender.abi
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/Safe.bin
  build/lender/lender.go
  build/marketplace/marketplace.go
  build/redeemer/redeemer.go
  pkg/lendertesting/dep.go
  pkg/lendertesting/lend_test.go
  test/lender/Element.bin
  test/lender/INotional.abi
  test/lender/INotional.bin
  test/lender/Interfaces.sol
  test/lender/Lender.abi
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/Safe.bin
  test/lender/lender.go
  test/marketplace/marketplace.go
  test/mocks/Notional.abi
  test/mocks/Notional.bin
  test/mocks/Notional.sol
  test/mocks/apwine.go
  test/mocks/apwinetoken.go
  test/mocks/element.go
  test/mocks/elementtoken.go
  test/mocks/erc20.go
  test/mocks/marketplace.go
  test/mocks/notional.go
  test/mocks/pendle.go
  test/mocks/pendletoken.go
  test/mocks/sense.go
  test/mocks/sensetoken.go
  test/mocks/swivel.go
  test/mocks/tempus.go
  test/mocks/tempustoken.go
  test/mocks/yield.go
  test/mocks/yieldtoken.go
  test/mocks/zctoken.go
  test/redeemer/redeemer.go
Labels: enhancement

#299 Implement redeem on notional
  build/redeemer/INotional.abi
  build/redeemer/INotional.bin
  build/redeemer/Interfaces.sol
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/redeemertesting/dep.go
  pkg/redeemertesting/redeem_test.go
  test/mocks/Notional.abi
  test/mocks/Notional.bin
  test/mocks/Notional.sol
  test/mocks/notional.go
  test/redeemer/INotional.abi
  test/redeemer/INotional.bin
  test/redeemer/Interfaces.sol
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: enhancement

#312 Add principal field to markets interface
  build/lender/Element.bin
  build/lender/IMarketPlace.abi
  build/lender/Interfaces.sol
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/Safe.bin
  build/lender/lender.go
  build/redeemer/IMarketPlace.abi
  build/redeemer/Interfaces.sol
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/lendertesting/lend_test.go
  pkg/redeemertesting/redeem_test.go
  test/lender/Element.bin
  test/lender/IMarketPlace.abi
  test/lender/Interfaces.sol
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/Safe.bin
  test/lender/lender.go
  test/marketplace/MarketPlace.bin
  test/marketplace/ZcToken.abi
  test/marketplace/ZcToken.bin
  test/marketplace/ZcToken.sol
  test/marketplace/marketplace.go
  test/mocks/MarketPlace.abi
  test/mocks/MarketPlace.bin
  test/mocks/MarketPlace.sol
  test/mocks/marketplace.go
  test/redeemer/IMarketPlace.abi
  test/redeemer/Interfaces.sol
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: bug

#316 Add lender to redeemer
  build/redeemer/Redeemer.abi
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/redeemertesting/constants.go
  pkg/redeemertesting/dep.go
  pkg/redeemertesting/redeem_test.go
  test/redeemer/Redeemer.abi
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: bug

#318 Normalize argument order to lend
  build/lender/Lender.abi
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/lender.go
  build/redeemer/Redeemer.abi
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/lendertesting/lend_test.go
  pkg/redeemertesting/redeem_test.go
  test/lender/Lender.abi
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/lender.go
  test/redeemer/Redeemer.abi
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: documentation

#325 Add natspec doc comment to fees attribute
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/lender.go
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/lender.go
Labels: documentation

#326 Retrieve redeemable balance from marketplace
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/redeemertesting/redeem_test.go
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: bug

#331 Implement mock of YieldSpace pools
  Makefile
  build/marketplace/IErc5095.abi
  build/marketplace/IErc5095.bin
  build/marketplace/IPool.abi
  build/marketplace/IPool.bin
  build/marketplace/Interfaces.sol
  build/marketplace/MarketPlace.bin
  build/marketplace/Safe.bin
  build/marketplace/marketplace.go
  test/marketplace/IErc5095.abi
  test/marketplace/IErc5095.bin
  test/marketplace/IPool.abi
  test/marketplace/IPool.bin
  test/marketplace/Interfaces.sol
  test/marketplace/MarketPlace.bin
  test/marketplace/Safe.bin
  test/marketplace/marketplace.go
  test/mocks/IErc5095.abi
  test/mocks/IErc5095.bin
  test/mocks/Pool.abi
  test/mocks/Pool.bin
  test/mocks/Pool.sol
  test/mocks/pool.go
Labels: enhancement

#333 Implement swaps between underlying and PTs in marketplace
  build/marketplace/IPool.abi
  build/marketplace/Interfaces.sol
  build/marketplace/MarketPlace.abi
  build/marketplace/MarketPlace.bin
  build/marketplace/MarketPlace.sol
  build/marketplace/Safe.bin
  build/marketplace/Safe.sol
  build/marketplace/marketplace.go
  pkg/illuminatetesting/dep.go
  pkg/illuminatetesting/marketplace_test.go
  test/marketplace/IPool.abi
  test/marketplace/Interfaces.sol
  test/marketplace/MarketPlace.abi
  test/marketplace/MarketPlace.bin
  test/marketplace/MarketPlace.sol
  test/marketplace/Safe.bin
  test/marketplace/Safe.sol
  test/marketplace/marketplace.go
  test/mocks/MarketPlace.abi
  test/mocks/MarketPlace.bin
  test/mocks/MarketPlace.sol
  test/mocks/Pool.abi
  test/mocks/Pool.bin
  test/mocks/Pool.sol
  test/mocks/marketplace.go
  test/mocks/pool.go
Labels: enhancement

#337 Fix balance of calls
  build/marketplace/MarketPlace.abi
  build/marketplace/MarketPlace.bin
  build/marketplace/MarketPlace.sol
  build/marketplace/marketplace.go
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/redeemertesting/redeem_test.go
  test/marketplace/MarketPlace.abi
  test/marketplace/MarketPlace.bin
  test/marketplace/MarketPlace.sol
  test/marketplace/marketplace.go
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: bug

#339 Remove argument names from interface files
  build/marketplace/IPool.abi
  build/marketplace/Interfaces.sol
  build/marketplace/MarketPlace.bin
  build/marketplace/Safe.bin
  build/marketplace/marketplace.go
  build/redeemer/IPendle.abi
  build/redeemer/ISense.abi
  build/redeemer/IYieldToken.abi
  build/redeemer/Interfaces.sol
  build/redeemer/Redeemer.bin
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  test/marketplace/IPool.abi
  test/marketplace/Interfaces.sol
  test/marketplace/MarketPlace.bin
  test/marketplace/Safe.bin
  test/marketplace/marketplace.go
  test/redeemer/IPendle.abi
  test/redeemer/ISense.abi
  test/redeemer/IYieldToken.abi
  test/redeemer/Interfaces.sol
  test/redeemer/Redeemer.bin
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: documentation

#341 Deposit to aave pool
  Makefile
  build/lender/Element.bin
  build/lender/IAave.abi
  build/lender/IAave.bin
  build/lender/Interfaces.sol
  build/lender/Lender.abi
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/Safe.bin
  build/lender/Safe.sol
  build/lender/lender.go
  pkg/lendertesting/dep.go
  pkg/lendertesting/lend_test.go
  test/lender/Element.bin
  test/lender/IAave.abi
  test/lender/IAave.bin
  test/lender/Interfaces.sol
  test/lender/Lender.abi
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/Safe.bin
  test/lender/Safe.sol
  test/lender/lender.go
  test/mocks/Aave.abi
  test/mocks/Aave.bin
  test/mocks/Aave.sol
  test/mocks/aave.go
Labels: enhancement

#346 Generate docs for all contracts
  README.md
  docs/lender/Any.md
  docs/lender/Cast.md
  docs/lender/Element.md
  docs/lender/IAPWineRouter.md
  docs/lender/IAPWineToken.md
  docs/lender/IAave.md
  docs/lender/IElement.md
  docs/lender/IElementToken.md
  docs/lender/IErc20.md
  docs/lender/IErc20Metadata.md
  docs/lender/IMarketPlace.md
  docs/lender/INotional.md
  docs/lender/IPendle.md
  docs/lender/IPendleToken.md
  docs/lender/ISense.md
  docs/lender/ISenseToken.md
  docs/lender/ISwivel.md
  docs/lender/ITempus.md
  docs/lender/IYield.md
  docs/lender/IZcToken.md
  docs/lender/Lender.md
  docs/lender/MarketPlace.md
  docs/lender/Safe.md
  docs/lender/Swivel.md
  docs/marketplace/IErc20.md
  docs/marketplace/IErc5095.md
  docs/marketplace/IPool.md
  docs/marketplace/MarketPlace.md
  docs/marketplace/Safe.md
  docs/marketplace/ZcToken.md
  docs/redeemer/IAPWine.md
  docs/redeemer/IElementToken.md
  docs/redeemer/IErc20.md
  docs/redeemer/IMarketPlace.md
  docs/redeemer/INotional.md
  docs/redeemer/IPendle.md
  docs/redeemer/ISense.md
  docs/redeemer/ISwivel.md
  docs/redeemer/ITempus.md
  docs/redeemer/IYield.md
  docs/redeemer/IYieldToken.md
  docs/redeemer/IZcToken.md
  docs/redeemer/MarketPlace.md
  docs/redeemer/Redeemer.md
  docs/redeemer/Safe.md
Labels: documentation

#349 Verify maturity and underlying
  build/lender/Element.bin
  build/lender/IAPWineToken.abi
  build/lender/ISense.abi
  build/lender/ISenseAMM.abi
  build/lender/ISenseAMM.bin
  build/lender/Interfaces.sol
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/Safe.bin
  build/lender/lender.go
  pkg/lendertesting/lend_test.go
  test/lender/Element.bin
  test/lender/IAPWineToken.abi
  test/lender/ISense.abi
  test/lender/ISenseAMM.abi
  test/lender/ISenseAMM.bin
  test/lender/Interfaces.sol
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/Safe.bin
  test/lender/lender.go
  test/mocks/APWineToken.abi
  test/mocks/APWineToken.bin
  test/mocks/APWineToken.sol
  test/mocks/Sense.abi
  test/mocks/Sense.bin
  test/mocks/Sense.sol
  test/mocks/apwinetoken.go
  test/mocks/sense.go
Labels: Illuminate

#351 Check illuminate redemption is occurring after maturity
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/redeemertesting/redeem_test.go
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: Illuminate

#352 Verify approvals in lender
  build/lender/Lender.abi
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/lender.go
  build/marketplace/MarketPlace.bin
  build/marketplace/MarketPlace.sol
  build/marketplace/marketplace.go
  build/redeemer/Redeemer.bin
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/illuminatetesting/marketplace_test.go
  pkg/lendertesting/lend_test.go
  test/lender/Lender.abi
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/lender.go
  test/marketplace/MarketPlace.bin
  test/marketplace/MarketPlace.sol
  test/marketplace/marketplace.go
  test/redeemer/Redeemer.bin
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: Illuminate

#353 Add custom errors
  build/lender/Lender.abi
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/lender.go
  build/marketplace/MarketPlace.abi
  build/marketplace/MarketPlace.bin
  build/marketplace/MarketPlace.sol
  build/marketplace/ZcToken.abi
  build/marketplace/ZcToken.bin
  build/marketplace/ZcToken.sol
  build/marketplace/marketplace.go
  build/redeemer/Redeemer.abi
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  test/lender/Lender.abi
  test/lender/Lender.bin
  test/lender/Lender.sol
  test/lender/lender.go
  test/marketplace/MarketPlace.abi
  test/marketplace/MarketPlace.bin
  test/marketplace/MarketPlace.sol
  test/marketplace/marketplace.go
  test/mocks/aave.go
  test/mocks/apwine.go
  test/mocks/apwinetoken.go
  test/mocks/element.go
  test/mocks/elementtoken.go
  test/mocks/erc20.go
  test/mocks/marketplace.go
  test/mocks/notional.go
  test/mocks/pendle.go
  test/mocks/pendletoken.go
  test/mocks/pool.go
  test/mocks/sense.go
  test/mocks/sensetoken.go
  test/mocks/swivel.go
  test/mocks/tempus.go
  test/mocks/tempustoken.go
  test/mocks/yield.go
  test/mocks/yieldtoken.go
  test/mocks/zctoken.go
  test/redeemer/Redeemer.abi
  test/redeemer/Redeemer.bin
  test/redeemer/Redeemer.sol
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
  test/tokens/ZcToken.sol
Labels: enhancement, Illuminate

#361 Implement the rest of the router interface
  .prettierrc
  build/lender/Element.bin
  build/lender/Interfaces.sol
  build/lender/Lender.bin
  build/lender/Lender.sol
  build/lender/Safe.bin
  build/lender/lender.go
  build/marketplace/IPool.abi
  build/marketplace/Interfaces.sol
  build/marketplace/MarketPlace.abi
  build/marketplace/MarketPlace.bin
  build/marketplace/MarketPlace.sol
  build/marketplace/Safe.bin
  build/marketplace/Safe.sol
  build/marketplace/marketplace.go
  build/redeemer/IElementToken.abi
  build/redeemer/ISwivel.abi
  build/redeemer/IYield.abi
  build/redeemer/Interfaces.sol
  build/redeemer/Redeemer.bin
  build/redeemer/Redeemer.sol
  build/redeemer/Safe.bin
  build/redeemer/redeemer.go
  pkg/illuminatetesting/marketplace_test.go
  test/lender/Element.bin
  test/lender/Interfaces.sol
  test/lender/Lender.bin
  test/lender/Safe.bin
  test/lender/lender.go
  test/marketplace/IPool.abi
  test/marketplace/Interfaces.sol
  test/marketplace/MarketPlace.abi
  test/marketplace/MarketPlace.bin
  test/marketplace/MarketPlace.sol
  test/marketplace/Safe.bin
  test/marketplace/Safe.sol
  test/marketplace/marketplace.go
  test/mocks/Pool.abi
  test/mocks/Pool.bin
  test/mocks/Pool.sol
  test/mocks/pool.go
  test/redeemer/IElementToken.abi
  test/redeemer/ISwivel.abi
  test/redeemer/IYield.abi
  test/redeemer/Interfaces.sol
  test/redeemer/Redeemer.bin
  test/redeemer/Safe.bin
  test/redeemer/redeemer.go
Labels: Illuminate

#383 implement, test the Erc4626 interface for transactions
  Makefile
  build/swivel/IErc4626.abi
  build/swivel/IErc4626.bin
  build/swivel/Interfaces.sol
  build/swivel/Safe.bin
  build/swivel/Swivel.bin
  build/swivel/Swivel.sol
  build/swivel/swivel.go
  pkg/swiveltesting/dep.go
  pkg/swiveltesting/initiate_zctoken_filling_vault_initiate_test.go
  test/mocks/Erc4626.abi
  test/mocks/Erc4626.bin
  test/mocks/Erc4626.sol
  test/mocks/erc4626.go
  test/swivel/IErc4626.abi
  test/swivel/IErc4626.bin
  test/swivel/Interfaces.sol
  test/swivel/Safe.bin
  test/swivel/Swivel.bin
  test/swivel/Swivel.sol
  test/swivel/swivel.go
Labels: SWIV3

#385 Feat/aave interface
  Makefile
  build/swivel/IAave.abi
  build/swivel/IAave.bin
  build/swivel/Interfaces.sol
  build/swivel/Safe.bin
  build/swivel/Swivel.abi
  build/swivel/Swivel.bin
  build/swivel/Swivel.sol
  build/swivel/swivel.go
  pkg/swiveltesting/dep.go
  pkg/swiveltesting/redeem_vault_interest_test.go
  test/mocks/AavePool.abi
  test/mocks/AavePool.bin
  test/mocks/AavePool.sol
  test/mocks/YearnVault.bin
  test/mocks/YearnVault.sol
  test/mocks/aavepool.go
  test/mocks/yearnvault.go
  test/swivel/IAave.abi
  test/swivel/IAave.bin
  test/swivel/Interfaces.sol
  test/swivel/Safe.bin
  test/swivel/Swivel.abi
  test/swivel/Swivel.bin
  test/swivel/Swivel.sol
  test/swivel/swivel.go
Labels: SWIV3
